### ISSUE TITLE
Read permissions for units

### ISSUE THREAD

**Issue by Harmageddon** [openbase/bco.authentication#10]
**Problem:** UnitController provide Informers to automatically publish state changes.
**Possible solutions:**
1. Informers only publish state changes that are visible for the public.
2. Informers publish that there are changes, remotes have to pull detailled information about what changed, filtered by permission.

**Comment by pLeminoq** [comment]
The implementation will contain a combination of both ideas.

1. The informer only publishes information visible for the public
2. Remotes which are authenticated ignore this information but use it as the trigger to request information filtered by permission.

This could always be improved by merging the state published for all users with the current state and testing if a follow up request with authentication is necessary.

**Comment by pLeminoq** [comment]
The basic implementation is finished on the branches:
* feature-communication-service-transaction-id: jul, bco.authentication
* feature-unit-read-permission: bco.registry, bco.dal
