### ISSUE TITLE
Implement error handling for authentication methods

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.authentication#15]
Currently the methods used for authentication just throw a RejectedException. Thishas  to be enhanced so that it is clear what went wrong and what the client has to do to fix it.
E.g. differentiate between incorrect password and user not found

**Comment by DivineThreepwood** [comment]
Was this not already solved last wednesday?

**Comment by Harmageddon** [comment]
It's almost done, I still have to update some documentation.
