### ISSUE TITLE
Prioritize client's or user's permissions in case those of client's are higher

### ISSUE THREAD

**Issue by tsafs** [openbase/bco.authentication#30]
Which permissions should be considered/preferred, in case a user logged in on a registered client and the client has more permissions than the user?

In case the client's permissions should be preferred, as of now the system would have to manage two ClientServerTickets in parallel, because both client and user would have to be authenticated. 

In case the user's permissions should always be preferred, no matter if they're lower than the client's or not, nothing would have change. If a user is logged in, it's permissions would always be checked. In case no user is logged in, the client's permissions would be checked.

**Comment by DivineThreepwood** [comment]
Outdated.
