### ISSUE TITLE
IP address is not set during authentication process

### ISSUE THREAD

**Issue by Harmageddon** [openbase/bco.authentication#48]
ATM, we set an empty string for the client's IP address inside the various Kerberos tickets.

**Comment by pLeminoq** [comment]
I don't think the IP address is really necessary for kerberos authentication. This should be looked up and if its the case the address can be removed from the ticket.

**Comment by DivineThreepwood** [comment]
Removed from epic because this is not a part of the core framework.

**Comment by pLeminoq** [comment]
The IP address is definitely not required for the authentication. So, it does not have to be set and will be removed from the protobuf type in the future. The field has been marked as deprecated in commit openbase/type@cf15760e5d25d97dffbc706fcda60a39177a869c
