### ISSUE TITLE
References to filtered units

### ISSUE THREAD

**Issue by Harmageddon** [openbase/bco.authentication#54]
If a user has no appropriate permission to view a unit, it will be filtered out by the `AuthorizationFilter`. However, the unit is still referenced elsewhere, for example in the unit list of its location. From this point, the remote can pick up the ID and try to retrieve the according unit from the registry. 

Can we filter the references or do we need to live with the exceptions being thrown in this case?

**Comment by DivineThreepwood** [comment]
In this case, the unit ids are now filtered. Issue in outdated anyway.
