### ISSUE TITLE
random SessionExpired Exception

### ISSUE THREAD

**Issue by Zukye** [openbase/bco.authentication#56]
I randomly get the following error even though I have just started bco and bcozy seconds before. Restarting does not always help, but sometimes it does 

ERROR o.o.b.a.c.AuthenticatorController ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestClientServerTicket(TicketAuthenticatorWrapper)]!
05:06:34.857 [Thread-39] ERROR o.o.b.a.c.AuthenticatorController  ╚══╦═⚀ Could not invoke Method[Class requestClientServerTicket(TicketAuthenticatorWrapper)]!
05:06:34.857 [Thread-39] ERROR o.o.b.a.c.AuthenticatorController     ╚══╦═⚀ org.openbase.jul.exception.RejectedException: Session expired
05:06:34.857 [Thread-39] ERROR o.o.b.a.c.AuthenticatorController        ╚════⚀ Session expired

**Comment by pLeminoq** [comment]
Does this still happen? If yes reopen.
