### ISSUE TITLE
Session has been expired during tests

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#59]
<pre>
 49 Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 13.143 sec <<< FAILURE! - in org.openbase.bco.manager.device.test.remote.authentication.ColorableLightRemoteWithAuthenticat    ionTest
 48 testSetColorWithUserWithoutAuthentication(org.openbase.bco.manager.device.test.remote.authentication.ColorableLightRemoteWithAuthenticationTest)  Time elapsed: 6.537 sec  <<< ERROR!
 47 org.openbase.jul.exception.CouldNotPerformException: Your session has expired. You have been logged out for security reasons. Please log in again.
 46     at org.openbase.bco.manager.device.test.remote.authentication.ColorableLightRemoteWithAuthenticationTest.testSetColorWithUserWithoutAuthentication(ColorableLightRemoteWithAuthenticati    onTest.java:184)
 45 
 44 testSetColorWithClientWithoutAuthentication(org.openbase.bco.manager.device.test.remote.authentication.ColorableLightRemoteWithAuthenticationTest)  Time elapsed: 0.022 sec  <<< ERROR!
 43 java.util.concurrent.ExecutionException: org.openbase.jul.exception.CouldNotPerformException: Could not call remote Method[registerUserConfig(UnitConfig)] on Scope[/test/divine/registry/u    ser/ctrl/].
 42     at org.openbase.bco.manager.device.test.remote.authentication.ColorableLightRemoteWithAuthenticationTest.testSetColorWithClientWithoutAuthentication(ColorableLightRemoteWithAuthentica    tionTest.java:112)
 41 Caused by: org.openbase.jul.exception.CouldNotPerformException: Could not call remote Method[registerUserConfig(UnitConfig)] on Scope[/test/divine/registry/user/ctrl/].
 40 Caused by: java.util.concurrent.ExecutionException: 
 39 rsb.RSBException: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUserConfig(UnitConfig)]! Details: Could not invoke Method[Class registerUserCo    nfig(UnitConfig)]!
 38 org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUserConfig(UnitConfig)]!
 37     at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:99)
 36     at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101)
 35     at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)
 34 Caused by: java.lang.reflect.InvocationTargetException
 33     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 32     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 31     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 30     at java.lang.reflect.Method.invoke(Method.java:498)
 29     at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:80)
 28     ... 2 more
 27 Caused by: org.openbase.bco.authentication.lib.exception.SessionExpiredException: Your session has expired!
 26     at org.openbase.bco.authentication.lib.SessionManager.isAuthenticated(SessionManager.java:492)
 25     at org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.requestAuthenticatedAction(AuthenticatedServiceProcessor.java:153)
 24     at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.registerUnitConfig(UnitRegistryRemote.java:246)
 23     at org.openbase.bco.registry.user.core.UserRegistryController.registerUserConfig(UserRegistryController.java:135)
 22     ... 7 more
 21 
 20 Caused by: rsb.RSBException: 
 19 org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUserConfig(UnitConfig)]! Details: Could not invoke Method[Class registerUserConfig(UnitConfig)]!
 18 org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class registerUserConfig(UnitConfig)]!
 17     at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:99)
 16     at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101)
 15     at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)
 14 Caused by: java.lang.reflect.InvocationTargetException
 13     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 12     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 11     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 10     at java.lang.reflect.Method.invoke(Method.java:498)
  9     at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:80)
  8     ... 2 more
  7 Caused by: org.openbase.bco.authentication.lib.exception.SessionExpiredException: Your session has expired!
  6     at org.openbase.bco.authentication.lib.SessionManager.isAuthenticated(SessionManager.java:492)
  5     at org.openbase.bco.authentication.lib.AuthenticatedServiceProcessor.requestAuthenticatedAction(AuthenticatedServiceProcessor.java:153)
  4     at org.openbase.bco.registry.unit.remote.UnitRegistryRemote.registerUnitConfig(UnitRegistryRemote.java:246)
  3     at org.openbase.bco.registry.user.core.UserRegistryController.registerUserConfig(UserRegistryController.java:135)
  2     ... 7 more
</pre>

**Comment by DivineThreepwood** [comment]
Timeout has been extended right?

**Comment by pLeminoq** [comment]
Yes, the timeout has been extended to one minute in tests.
