### ISSUE TITLE
Authentification: User/Password

### ISSUE THREAD

**Issue by Harmageddon** [openbase/bco.authentication#6]
* Login using `userID@clientID`

**Comment by tsafs** [comment]
Ich habe das so verstanden, dass wir die Notation andersherum nehmen. So habe ich das im #28 auch implementiert

**Comment by Harmageddon** [comment]
Dann wäre es gut, wenn du das einmal umdrehen könntest. Wird in der Reihenfolge überall verwendet (z.B. auf jedem Unix-System bist du username@machinename), deshalb würde ich das bei uns ungern andersrum machen.

**Comment by tsafs** [comment]
okay
