### ISSUE TITLE
reenabled automated bco.authentication tests in test module pom

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#69]
Currently the tests of the bco.authentication test package are disabled via pom.
Fix tests and reenable the ci tests.

**Comment by pLeminoq** [comment]
Enabled and fixed test in commit b4c9b1246fa9ab2b2a41e13eef35f2e912748eed. The issue was that singletons where not cleaned up properly between tests causing inferences. The commit includes a test class others can extend from which performs the setup before and cleanup after the test.
