### ISSUE TITLE
Enhance Credential Store

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.authentication#72]
Currently the credential store uses LoginCredentialChange values for serialization. The problem is that this does not really match the data which is saved. E.g. the type contains old and new credentials.
Furthermore it would be good to now if the saved credentials belong to a password hash or a private key.

**Comment by DivineThreepwood** [comment]
If this issue causes any external api changes, please resolve it within the 2.0 release.

**Comment by pLeminoq** [comment]
Yes, this issue will definitely entail API changes. At least the protobuf type which is used to store and change credentials will change.

**Comment by DivineThreepwood** [comment]
Could you please apply the api changes already to the credential store type?
Changing the type when bco is released would require a auto update routine which we should avoid.
And, if possible, already refactor the public api interface so we can avoid public api changes within 2.0.X

* Clarify if Base64 decoding is still required.
* add symmetric / asymmetric flag
* use two fields for user and client id and remove @ separation

**Comment by DivineThreepwood** [comment]
Please update Issue state.

**Comment by pLeminoq** [comment]
This issue has been implemented on a feature branch and is already merged into the master.

* A symmetric flag has been added which allows anybody to user either symmetric or asymmetric encryption
* To remove the @ separator the UserClientPair type has been introduced.
* Base64 is de-/encoding is still required for de-/serialization
