### ISSUE TITLE
CPU Burn after kerberos ticket expires

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#73]
Currently after 7 days (kerberos ticket timeout) all bco components freeze (as well openhab where the sitemap is not further responding). The cpu usage of at least one core is on limit. 

Please investigate and write unit tests:
* why is the ticket not extended during daily client - server interaction.
* why in the reconnect not working after the ticket expires
    * openhab currently uses the admin account for authentication. The openhab user does not own its own home folder there is no credential store available. Could this be the reason for the failing reconnect and if yes how can we handle that?
   * it seems that the client does not realise that its ticket in invalid. 
* why is the cpu usage that high?
    * maybe the clients performing a DOS attack because of the missing invalid ticket feedback. So maybe they continuously reapply the same actions after the authentication fails?

bco log:
<pre>
21:48:43.399 [pool-1-thread-14127] ERROR o.o.b.a.l.AuthenticatedServerManager ???? Your session has expired!
21:48:43.399 [pool-1-thread-14127] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
21:48:43.400 [pool-1-thread-14132] ERROR o.o.b.a.l.AuthenticatedServerManager ???? Your session has expired!
21:48:43.400 [pool-1-thread-14132] ERROR o.o.b.a.l.AuthenticatedServerManager =====================================
21:48:43.400 [pool-1-thread-14058] ERROR o.o.b.r.t.c.TemplateRegistryController ???? Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of TemplateRegistryController[/registry/template/status/]!
21:48:43.400 [pool-1-thread-14058] ERROR o.o.b.r.t.c.TemplateRegistryController  ?????? Your session has expired!
21:48:43.400 [pool-1-thread-14058] ERROR o.o.b.r.t.c.TemplateRegistryController =====================================
Dec 12, 2018 9:48:43 PM rsb.patterns.LocalMethod internalNotify
WARNING: Exception during method invocation in participant: /registry/template/ctrl/requestDataAuthenticated/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of TemplateRegistryController[/registry/template/status/]!
21:48:43.401 [pool-1-thread-13968] ERROR o.o.b.r.a.c.ActivityRegistryController ???? Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
21:48:43.401 [pool-1-thread-13968] ERROR o.o.b.r.a.c.ActivityRegistryController  ?????? Your session has expired!
21:48:43.401 [pool-1-thread-13968] ERROR o.o.b.r.a.c.ActivityRegistryController =====================================
Dec 12, 2018 9:48:43 PM rsb.patterns.LocalMethod internalNotify
WARNING: Exception during method invocation in participant: /registry/activity/ctrl/requestDataAuthenticated/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class requestDataAuthenticated(TicketAuthenticatorWrapper)] of ActivityRegistryController[/registry/activity/status/]!
</pre>

openhab device manager log:
<pre>
22:20:50.308 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
22:21:05.321 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote ???? TimeoutException
22:21:05.322 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote =====================================
22:21:05.322 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
22:21:20.332 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote ???? TimeoutException
22:21:20.332 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote =====================================
22:21:20.332 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
22:21:35.342 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote ???? TimeoutException
22:21:35.342 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote =====================================
22:21:35.343 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
22:21:50.362 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote ???? TimeoutException
22:21:50.363 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote =====================================
22:21:50.363 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
22:22:05.372 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote ???? TimeoutException
22:22:05.373 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote =====================================
22:22:05.373 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
22:22:20.382 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote ???? TimeoutException
22:22:20.382 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote =====================================
22:22:20.382 [pool-1-thread-99] WARN  o.o.b.r.t.r.TemplateRegistryRemote Controller[/registry/template/] does not respond!  Next retry timeout in 30 sec.
</pre>

**Comment by pLeminoq** [comment]
Fixed after commits:

* openbase/jul@babc90f75296826cc0556c94056013521a500af6
* openbase/bco.authentication@b277f9038809075eb5058a5eaaa49ee9689414cf

Problems were that the ReLoginFuture did not handle SessionExpiredExceptions and that the RSBCommunicationService would loop if the requestStatus RPC caused an exception.
