### ISSUE TITLE
Please revise code change to fix bug where new tickets are directly outdated.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.authentication#74]
Please revise commit: bco.authentication@428e1d7

* In my view the unit of the max_server_diff_time was just wrong. I changed it from nano to milliseconds.
* I extended the ticket interval check with the max_server_diff_time to both directions to fix the issue.

Can you please validate that everything is fine?

**Comment by pLeminoq** [comment]
Code changes in the commit seem fine to me!
